################################################################################
##                                                                            ##
##  FILE: alsp_resa.inc                                                       ##
##                                                                            ##
##  DATE CREATED:   April 30, 1992                                            ##
##                                                                            ##
##  DATE MODIFIED:                                                            ##
##                                                                            ##
##  AUTHORS:        Carol L. Kropp                                            ##
##                                                                            ##
##  MODIFIERS:                                                                ##
##                                                                            ##
##  LINKS WITH:                                                               ##
##                                                                            ##
##  PURPOSE:        Includes the RESA *.inc files used within the model       ##
##                  specific ALSP translator.                                 ##
##                                                                            ##
################################################################################

include "orders.inc"         
include "ascii.inc"         
include "macros.inc"         

include "bbctl.inc"         
include "bbcode.inc"         

include "bbagd.inc"               # ground units

include "bbboy.inc"         
include "bbctm.inc"         
include "bbdeq.inc"               # units
include "bbjew.inc"         
include "bbown.inc"         
include "bbunt.inc"         

include "bbaml.inc"               # maintenance logs
include "bbbml.inc"         

include "bbacc.inc"               # unit characteristics
include "bbshc.inc"         

include "bbrad.inc"               # sensor characteristics
include "bbiff.inc"         
include "bbjam.inc"         

include "bbbom.inc"               # weapon characteristics
include "bbcmc.inc"         
include "bbmc.inc"         
include "bbpng.inc"         
include "bbsob.inc"         
include "bbson.inc"         
include "bbtor.inc"         
include "bbtat.inc"         
include "bbtrp.inc"         

include "bbpim.inc"         
include "bbvue.inc"         

include "bbbtt.inc"              # for BE and TIN data - clk 12/97 (E1911)

include "cenglog.inc"         
include "hseng.inc"         

