define (PI,3.14159265)
define ($PI,3.14159265)
define (PI2,6.283185308)
define ($PI2,6.283185308)
define ($DEGRAD,57.2957795)
define($EAIR,1)
define($ESUB,2)
define($ESURF,3)
define($FAIR,4)
define($FSUB,5)
define($FSURF,6)
define($UAIR,7)
define($USUB,8)
define($USURF,9)
define($UB,10)
define($UO,11)
define($UN,12)
define($XMARK,13)
define($BASE,14)

define($BUILD$ENVELOPE,0)		# Function code for doenv subroutine
define($DRAW$ENVELOPE,1)		# Function code for doenv subroutine

define ($MAX$ENV$CIRCLES,50)    #max number of circles in an envelope

define($MERCATOR,1)			# Mercator projection code
define($NOPROJ,0)			# No projection code
