      SUBROUTINE BMOV (INBSTR,INLEN,OUTBSTR,OUTLEN)
      INTEGER INBSTR(10)
      INTEGER INLEN
      INTEGER OUTBSTR(0:10)
      INTEGER OUTLEN
      INTEGER IW,ISB,IEB,IWLEN,INWORD
      INTEGER OW,OWSB,OSB,OWEB,OWREM,OWLEN
      INTEGER MASK(0:32)
      DATA MASK / 0,'0001'X,'0003'X,'0007'X,'000F'X,'001F'X,'003F'X,    
     *'007F'X,'00FF'X,'01FF'X,'03FF'X,'07FF'X,'0FFF'X,'1FFF'X,'3FFF'X,  
     *'7FFF'X,'FFFF'X,'01FFFF'X,'03FFFF'X,'07FFFF'X,'0FFFFF'X,'1FFFFF'X,
     * '3FFFFF'X,'7FFFFF'X,'FFFFFF'X,'01FFFFFF'X,'03FFFFFF'X,           
     *'07FFFFFF'X,'0FFFFFFF'X,'1FFFFFFF'X,'3FFFFFFF'X,'7FFFFFFF'X,      
     *'37777777777'O/
      IW =0
      ISB=0
23000 IF(.NOT.(ISB.LT.INLEN))GOTO 23002
      IEB =MIN (31,INLEN -ISB -1)
      IW =IW +1
      IWLEN =IEB +1
      INWORD =IAND(INBSTR(IW),MASK(IWLEN))
      OSB =OUTLEN
      OW =ISHFT (OSB,-5)
      OWSB =IAND(OSB,31)
      OWREM =32 -OWSB
      OWLEN =MIN (IWLEN,OWREM)
      OUTBSTR(OW)=IOR(IAND(OUTBSTR(OW),NOT(ISHFT(MASK(OWLEN),OWSB))),ISH
     *FT(IAND(INWORD,MASK(OWLEN)),OWSB))
      IF(.NOT.(INLEN.GT.OWREM))GOTO 23003
      OW =OW +1
      INWORD =ISHFT (INWORD,-OWLEN)
      OWLEN =IWLEN -OWREM
      OWSB =0
      OUTBSTR(OW)=IOR(IAND(OUTBSTR(OW),NOT(ISHFT(MASK(OWLEN),OWSB))),ISH
     *FT(IAND(INWORD,MASK(OWLEN)),OWSB))
23003 CONTINUE
      OUTLEN =OUTLEN +IWLEN
23001 ISB=ISB+32
      GOTO 23000
23002 CONTINUE
      RETURN
      END
      INTEGER FUNCTION BSUBSTR(INBSTR,INST,INLEN)
      INTEGER INBSTR(0:10)
      INTEGER INLEN
      INTEGER BOUT,BOUTT
      INTEGER IWSB,IW,IWREM,IWLEN,IS,INST
      INTEGER MASK(0:32)
      DATA MASK / 0,'0001'X,'0003'X,'0007'X,'000F'X,'001F'X,'003F'X,    
     *'007F'X,'00FF'X,'01FF'X,'03FF'X,'07FF'X,'0FFF'X,'1FFF'X,'3FFF'X,  
     *'7FFF'X,'FFFF'X,'01FFFF'X,'03FFFF'X,'07FFFF'X,'0FFFFF'X,'1FFFFF'X,
     * '3FFFFF'X,'7FFFFF'X,'FFFFFF'X,'01FFFFFF'X,'03FFFFFF'X,           
     *'07FFFFFF'X,'0FFFFFFF'X,'1FFFFFFF'X,'3FFFFFFF'X,'7FFFFFFF'X,      
     *'37777777777'O/
      IS =INST -1
      IW =ISHFT (IS,-5)
      IWSB =IAND(IS,31)
      IWREM =32 -IWSB
      IWLEN =MIN (INLEN,IWREM)
      BOUT =IAND(ISHFT(INBSTR(IW),-(IWSB)),MASK(IWLEN))
      IF(.NOT.(INLEN.GT.IWREM))GOTO 23005
      IW =IW +1
      IWLEN =INLEN -IWREM
      IWSB =0
      BOUTT =IAND(ISHFT(INBSTR(IW),-(IWSB)),MASK(IWLEN))
      BOUT=IOR(IAND(BOUT,NOT(ISHFT(MASK(IWLEN),IWREM))),ISHFT(IAND(BOUTT
     *,MASK(IWLEN)),IWREM))
23005 CONTINUE
      BSUBSTR=(BOUT )
      RETURN
      END
