      SUBROUTINE PUT_CONSOLE (LINE)
      IMPLICIT NONE
      LOGICAL*1 LINE(400)
      INTEGER LENGTH
      CALL ECHOH(LINE,LENGTH(LINE))
      CALL ECHOR
      RETURN
      END
      SUBROUTINE PUT_CONSOLE_V (LINE)
      IMPLICIT NONE
      CHARACTER *(*) LINE
      CALL ECHOVT(LINE)
      CALL ECHOR
      RETURN
      END
      SUBROUTINE PUT_CONSOLE_ERR_V (MSGV,ERROR_CODE)
      IMPLICIT NONE
      CHARACTER *(*) MSGV
      INTEGER ERROR_CODE
      CALL PUT_CONSOLE_ERR (%REF(MSGV),ERROR_CODE)
      RETURN
      END
      SUBROUTINE PUT_CONSOLE_ERR (MSG,ERROR_CODE)
      IMPLICIT NONE
      INTEGER K,RC,ERROR_CODE
      LOGICAL*1 MSG(100),WORK(400)
      K =0
      IF(.NOT.(MSG(1).NE.0))GOTO 23000
      CALL SMOVH (MSG,100,WORK,K)
      CALL SMOV (13,WORK,K)
      CALL SMOV (10,WORK,K)
23000 CONTINUE
      RC =ERROR_CODE
      CALL GETERR (RC,WORK(K+1))
      CALL PUT_CONSOLE (WORK)
      RETURN
      END
