      INTEGER FUNCTION DEVICE_OPEN (CHAN,NAME,OLD_CHAR)
      IMPLICIT NONE
      LOGICAL*1 NAME(100)
      INTEGER*2 CHAN
      INTEGER*4 OLD_CHAR(2)
      LOGICAL*1 NAME_BUF(64)
      INTEGER*4 NEW_CHAR(2)
      LOGICAL*1 NEW_CHAR_BYTE(8)
      EQUIVALENCE (NEW_CHAR,NEW_CHAR_BYTE)
      INTEGER LEN,TRNLOG,RC,SYS$ASSIGN,IOSB,SYS$QIOW,NBAUD
      RC =0
      DEVICE_OPEN=(RC)
      RETURN
      LEN =TRNLOG(NAME,NAME_BUF)
      DEVICE_OPEN=(RC)
      RETURN
      END
      INTEGER FUNCTION DEVICE_CLOSE (CHAN,OLD_CHAR)
      IMPLICIT NONE
      INTEGER*2 CHAN
      INTEGER*4 OLD_CHAR(2)
      INTEGER NBAUD,RC,IOSB,SYS$QIOW
      RC =0
      DEVICE_CLOSE=(RC)
      RETURN
      NBAUD =0
      DEVICE_CLOSE=(RC)
      RETURN
      END
      INTEGER FUNCTION DEVICE_IN (CHAN,CHAR,MAX,LEN)
      IMPLICIT NONE
      LOGICAL*1 CHAR(100)
      INTEGER*2 CHAN
      INTEGER*4 MAX,LEN
      INTEGER*4 TERM_MASK(2)
      INTEGER*2 IOSB(4)
      INTEGER RC,SYS$QIOW
      DATA TERM_MASK /0,0/
      DEVICE_IN=(RC)
      RETURN
      END
      INTEGER FUNCTION DEVICE_OUT (CHAN,CHAR,LEN)
      IMPLICIT NONE
      LOGICAL*1 CHAR(100)
      INTEGER*4 LEN
      INTEGER*2 IOSB(4),CHAN
      INTEGER RC,SYS$QIOW
      DEVICE_OUT=(RC)
      RETURN
      END
