      SUBROUTINE PREPRX(FLAT,FLON,COSLAT,RMAX)
      IMPLICIT NONE
      REAL*4 REFLAT,REFLON,REFCOS,REFRNG,DLTMAX,RSQMAX,DLNMAX
      INTEGER UNT_REFERENCE
      REAL*4 SAV_REFLAT,SAV_REFLON,SAV_REFCOS,SAV_REFRNG,SAV_DLTMAX,SAV_
     *RSQMAX,SAV_DLNMAX
      INTEGER SAV_UNT_REFERENCE
      COMMON / PROXIM_COM / REFLAT,REFLON,REFCOS,RSQMAX,DLTMAX,DLNMAX,RE
     *FRNG,UNT_REFERENCE
      COMMON / SAV_PROXIM_COM / SAV_REFLAT,SAV_REFLON,SAV_REFCOS,SAV_RSQ
     *MAX,SAV_DLTMAX,SAV_DLNMAX,SAV_REFRNG,SAV_UNT_REFERENCE
CPAR$ PRIVATE / PROXIM_COM /
CPAR$ PRIVATE / SAV_PROXIM_COM /
      REAL FLAT,FLON,COSLAT,RMAX
      REFLAT =FLAT
      REFLON =FLON
      REFCOS =COSLAT
      REFCOS =MAX(REFCOS,0.0001)
      REFRNG =RMAX
      DLTMAX =RMAX *(3.141592654/ (180. *60.))
      RSQMAX =DLTMAX *DLTMAX
      DLNMAX =DLTMAX / REFCOS
      UNT_REFERENCE =0
      RETURN
      END
      SUBROUTINE PROXIM(FLAT,FLON,COSLAT,RANGE,BEAR)
      IMPLICIT NONE
      REAL*4 REFLAT,REFLON,REFCOS,REFRNG,DLTMAX,RSQMAX,DLNMAX
      INTEGER UNT_REFERENCE
      REAL*4 SAV_REFLAT,SAV_REFLON,SAV_REFCOS,SAV_REFRNG,SAV_DLTMAX,SAV_
     *RSQMAX,SAV_DLNMAX
      INTEGER SAV_UNT_REFERENCE
      COMMON / PROXIM_COM / REFLAT,REFLON,REFCOS,RSQMAX,DLTMAX,DLNMAX,RE
     *FRNG,UNT_REFERENCE
      COMMON / SAV_PROXIM_COM / SAV_REFLAT,SAV_REFLON,SAV_REFCOS,SAV_RSQ
     *MAX,SAV_DLTMAX,SAV_DLNMAX,SAV_REFRNG,SAV_UNT_REFERENCE
CPAR$ PRIVATE / PROXIM_COM /
CPAR$ PRIVATE / SAV_PROXIM_COM /
      REAL RANGE,DELLAT,FLAT,DELLON,FLON
      REAL HORIZ,COSLAT,RSQ,BEAR
      RANGE =-1.0
      DELLAT =FLAT -REFLAT
      IF(.NOT.(ABS(DELLAT).LE.DLTMAX))GOTO 23000
      DELLON =FLON -REFLON
23002 IF(.NOT.(DELLON.GT.3.141592654))GOTO 23003
      DELLON =DELLON -6.283185307
      GOTO 23002
23003 CONTINUE
23004 IF(.NOT.(DELLON.LE.-3.141592654))GOTO 23005
      DELLON =DELLON +6.283185307
      GOTO 23004
23005 CONTINUE
      IF(.NOT.(ABS(DELLON).LE.DLNMAX))GOTO 23006
      HORIZ =.5*(REFCOS+COSLAT)*DELLON
      RSQ =DELLAT*DELLAT +HORIZ*HORIZ
      IF(.NOT.(RSQ.LE.RSQMAX))GOTO 23008
      IF(.NOT.(DELLAT.EQ.0.0.AND.HORIZ.EQ.0.0))GOTO 23010
      RANGE =0.0
      BEAR =0.0
      GOTO 23011
23010 CONTINUE
      RANGE =SQRT(RSQ)*(180.*60./3.141592654)
      BEAR =ATAN2(HORIZ,DELLAT)
      IF(.NOT.(BEAR.LT.0.))GOTO 23012
      BEAR =BEAR +6.283185307
23012 CONTINUE
23011 CONTINUE
23008 CONTINUE
23006 CONTINUE
23000 CONTINUE
      RETURN
      END
      SUBROUTINE SAVPRX
      IMPLICIT NONE
      REAL*4 REFLAT,REFLON,REFCOS,REFRNG,DLTMAX,RSQMAX,DLNMAX
      INTEGER UNT_REFERENCE
      REAL*4 SAV_REFLAT,SAV_REFLON,SAV_REFCOS,SAV_REFRNG,SAV_DLTMAX,SAV_
     *RSQMAX,SAV_DLNMAX
      INTEGER SAV_UNT_REFERENCE
      COMMON / PROXIM_COM / REFLAT,REFLON,REFCOS,RSQMAX,DLTMAX,DLNMAX,RE
     *FRNG,UNT_REFERENCE
      COMMON / SAV_PROXIM_COM / SAV_REFLAT,SAV_REFLON,SAV_REFCOS,SAV_RSQ
     *MAX,SAV_DLTMAX,SAV_DLNMAX,SAV_REFRNG,SAV_UNT_REFERENCE
CPAR$ PRIVATE / PROXIM_COM /
CPAR$ PRIVATE / SAV_PROXIM_COM /
      SAV_REFLAT =REFLAT
      SAV_REFLON =REFLON
      SAV_REFCOS =REFCOS
      SAV_REFRNG =REFRNG
      SAV_RSQMAX =RSQMAX
      SAV_DLTMAX =DLTMAX
      SAV_DLNMAX =DLNMAX
      SAV_UNT_REFERENCE =UNT_REFERENCE
      RETURN
      END
      SUBROUTINE RESPRX
      IMPLICIT NONE
      REAL*4 REFLAT,REFLON,REFCOS,REFRNG,DLTMAX,RSQMAX,DLNMAX
      INTEGER UNT_REFERENCE
      REAL*4 SAV_REFLAT,SAV_REFLON,SAV_REFCOS,SAV_REFRNG,SAV_DLTMAX,SAV_
     *RSQMAX,SAV_DLNMAX
      INTEGER SAV_UNT_REFERENCE
      COMMON / PROXIM_COM / REFLAT,REFLON,REFCOS,RSQMAX,DLTMAX,DLNMAX,RE
     *FRNG,UNT_REFERENCE
      COMMON / SAV_PROXIM_COM / SAV_REFLAT,SAV_REFLON,SAV_REFCOS,SAV_RSQ
     *MAX,SAV_DLTMAX,SAV_DLNMAX,SAV_REFRNG,SAV_UNT_REFERENCE
CPAR$ PRIVATE / PROXIM_COM /
CPAR$ PRIVATE / SAV_PROXIM_COM /
      REFLAT =SAV_REFLAT
      REFLON =SAV_REFLON
      REFCOS =SAV_REFCOS
      REFRNG =SAV_REFRNG
      RSQMAX =SAV_RSQMAX
      DLTMAX =SAV_DLTMAX
      DLNMAX =SAV_DLNMAX
      UNT_REFERENCE =SAV_UNT_REFERENCE
      RETURN
      END
      SUBROUTINE TRACE_PROXIM (ICODE)
      IMPLICIT NONE
      INTEGER*4 IBB(10240000)
      INTEGER*2 IBBW(2,10240000)
      BYTE IBBB(4,10240000)
      REAL*8 CBB(5120000)
      REAL FBB(10240000)
      INTEGER IBBP(6,170)
      EQUIVALENCE (IBB,FBB,CBB,IBBW,IBBB)
      EQUIVALENCE (IBB(1025),IBBP)
      COMMON /BBOARD/ IBB
cpar$ private / BBoard / ! keep FORTRAN from assigning a global section
      INTEGER ISNAP_D , ISNAP_BEFORE_1 , ISNAP_BEFORE_2 , ISNAP_AFTER_1 
     *, ISNAP_AFTER_2
      COMMON / SNAP_COMMON / ISNAP_D , ISNAP_BEFORE_1 , ISNAP_BEFORE_2 ,
     * ISNAP_AFTER_1 , ISNAP_AFTER_2
cpar$ private / snap_common / ! no FORTRAN global section
      INTEGER LAST_MINUTE,COUNTERS(10)
      COMMON / TRACE_PROXIM_COM / LAST_MINUTE,COUNTERS
      INTEGER N
      INTEGER ICODE
      CHARACTER *8 T_NAMES_V(10)
      REAL*8 T_NAMES(10)
      EQUIVALENCE (T_NAMES_V,T_NAMES)
      DATA T_NAMES_V(1) / 'PREPRX  ' /
      DATA T_NAMES_V(2) / 'PROXIM  ' /
      DATA T_NAMES_V(3) / 'SAVPRX  ' /
      DATA T_NAMES_V(4) / 'RESPRX  ' /
      DATA T_NAMES_V(5) / 'GETRB   ' /
      DATA T_NAMES_V(6) / 'RLL2RB  ' /
      DATA T_NAMES_V(7) / 'PREPRX_M' /
      DATA T_NAMES_V(8) / 'PROXIM_M' /
      DATA T_NAMES_V(9) / 'GETRB_M ' /
      DATA T_NAMES_V(10) / 'Found!  ' /
      IF(.NOT.( IAND(ISHFT(IBB(3),-(0)),'0001'X).EQ.1))GOTO 23014
      IF(.NOT.(IBB(103).NE.LAST_MINUTE))GOTO 23016
      CALL ECHOR
      CALL ECHOV ('* Proxim @ ')
      CALL ECHOI(LAST_MINUTE)
      N =1
23018 IF(.NOT.(N.LE.10))GOTO 23020
      IF(.NOT.(COUNTERS(N).NE.0))GOTO 23021
      CALL ECHOV ('  ')
      CALL ECHOHN (T_NAMES(N),8)
      CALL ECHOV ('=')
      CALL ECHOI(COUNTERS(N))
      COUNTERS(N ) =0
23021 CONTINUE
23019 N=N+1
      GOTO 23018
23020 CONTINUE
      LAST_MINUTE =IBB(103)
23016 CONTINUE
      COUNTERS(ICODE) =COUNTERS(ICODE) +1
23014 CONTINUE
      END
      SUBROUTINE PSLANT (FLAT,FLON,IFALT,COSLAT,RMAX)
      IMPLICIT NONE
      COMMON /SLANT_COM/ REFLAT,REFLON,IREFAL,REFCOS,DLTMAX,DLNMAX,DALMA
     *X,RSQMAX
CPAR$ PRIVATE / SLANT_COM /
      REAL DLTMAX,RMAX,DLNMAX,COSLAT,DALMAX
      REAL RSQMAX,REFLAT,FLAT,REFLON,FLON,REFCOS
      INTEGER IREFAL,IFALT
      REFCOS =COSLAT
      REFCOS =MAX(REFCOS,0.0001)
      DLTMAX =RMAX *0.0174533/ 60.
      DLNMAX =DLTMAX / REFCOS
      DALMAX =RMAX *6076.1
      RSQMAX =RMAX *RMAX
      REFLAT =FLAT
      REFLON =FLON
      IREFAL =IFALT
      RETURN
      END
      SUBROUTINE SLRANG (FLAT,FLON,IFALT,COSLAT,HRANGE,RANGE,BEAR)
      IMPLICIT NONE
      COMMON /SLANT_COM/ REFLAT,REFLON,IREFAL,REFCOS,DLTMAX,DLNMAX,DALMA
     *X,RSQMAX
CPAR$ PRIVATE / SLANT_COM /
      REAL RANGE,DELLAT,FLAT,REFLAT,DLTMAX,DELLON
      REAL FLON,REFLON,DLNMAX,DELALT,DALMAX,REFCOS
      REAL X,Y,Z,W,U,COSLAT,RSQMAX,HRANGE,BEAR
      INTEGER IFALT,IREFAL
      RANGE =-1.
      DELLAT =FLAT -REFLAT
      IF(.NOT.(ABS(DELLAT).LE.DLTMAX))GOTO 23023
      DELLON =FLON -REFLON
23025 IF(.NOT.(DELLON.GT.3.141592654))GOTO 23026
      DELLON =DELLON -6.283185307
      GOTO 23025
23026 CONTINUE
23027 IF(.NOT.(DELLON.LE.-3.141592654))GOTO 23028
      DELLON =DELLON +6.283185307
      GOTO 23027
23028 CONTINUE
      IF(.NOT.(ABS(DELLON).LE.DLNMAX))GOTO 23029
      DELALT =IFALT -IREFAL
      IF(.NOT.(ABS(DELALT).LE.DALMAX))GOTO 23031
      X =(REFCOS+COSLAT)*DELLON*(.5*60.*57.29577951)
      Y =DELLAT *(60. *57.29577951)
      Z =DELALT *(1./6076.1)
      W =X*X +Y*Y
      U =W +Z*Z
      IF(.NOT.(U.LE.RSQMAX))GOTO 23033
      RANGE =SQRT(U)
      HRANGE =SQRT(W)
      IF(.NOT.(X.EQ.0.0.AND.Y.EQ.0.0))GOTO 23035
      BEAR =0.0
      GOTO 23036
23035 CONTINUE
      BEAR =ATAN2(X,Y)
      IF(.NOT.(BEAR.LT.0.))GOTO 23037
      BEAR =BEAR +6.283185307
23037 CONTINUE
23036 CONTINUE
23033 CONTINUE
23031 CONTINUE
23029 CONTINUE
23023 CONTINUE
      RETURN
      END
      SUBROUTINE INIT_URB
      IMPLICIT NONE
      INTEGER*4 IBB(10240000)
      INTEGER*2 IBBW(2,10240000)
      BYTE IBBB(4,10240000)
      REAL*8 CBB(5120000)
      REAL FBB(10240000)
      INTEGER IBBP(6,170)
      EQUIVALENCE (IBB,FBB,CBB,IBBW,IBBB)
      EQUIVALENCE (IBB(1025),IBBP)
      COMMON /BBOARD/ IBB
cpar$ private / BBoard / ! keep FORTRAN from assigning a global section
      INTEGER ISNAP_D , ISNAP_BEFORE_1 , ISNAP_BEFORE_2 , ISNAP_AFTER_1 
     *, ISNAP_AFTER_2
      COMMON / SNAP_COMMON / ISNAP_D , ISNAP_BEFORE_1 , ISNAP_BEFORE_2 ,
     * ISNAP_AFTER_1 , ISNAP_AFTER_2
cpar$ private / snap_common / ! no FORTRAN global section
      END
      SUBROUTINE PREPRX_M(INDX1,FLAT,FLON,COSLAT,RMAX)
      IMPLICIT NONE
      REAL*4 REFLAT,REFLON,REFCOS,REFRNG,DLTMAX,RSQMAX,DLNMAX
      INTEGER UNT_REFERENCE
      REAL*4 SAV_REFLAT,SAV_REFLON,SAV_REFCOS,SAV_REFRNG,SAV_DLTMAX,SAV_
     *RSQMAX,SAV_DLNMAX
      INTEGER SAV_UNT_REFERENCE
      COMMON / PROXIM_COM / REFLAT,REFLON,REFCOS,RSQMAX,DLTMAX,DLNMAX,RE
     *FRNG,UNT_REFERENCE
      COMMON / SAV_PROXIM_COM / SAV_REFLAT,SAV_REFLON,SAV_REFCOS,SAV_RSQ
     *MAX,SAV_DLTMAX,SAV_DLNMAX,SAV_REFRNG,SAV_UNT_REFERENCE
CPAR$ PRIVATE / PROXIM_COM /
CPAR$ PRIVATE / SAV_PROXIM_COM /
      REAL FLAT,FLON,COSLAT,RMAX
      INTEGER INDX1
      REFLAT =FLAT
      REFLON =FLON
      REFCOS =COSLAT
      REFCOS =MAX(REFCOS,0.0001)
      REFRNG =RMAX
      DLTMAX =RMAX *(3.141592654/ (180. *60.))
      RSQMAX =DLTMAX *DLTMAX
      DLNMAX =DLTMAX / REFCOS
      UNT_REFERENCE =INDX1
      RETURN
      END
      SUBROUTINE PROXIM_M(INDX2,FLAT,FLON,COSLAT,RANGE,BEARING)
      IMPLICIT NONE
      INTEGER*4 IBB(10240000)
      INTEGER*2 IBBW(2,10240000)
      BYTE IBBB(4,10240000)
      REAL*8 CBB(5120000)
      REAL FBB(10240000)
      INTEGER IBBP(6,170)
      EQUIVALENCE (IBB,FBB,CBB,IBBW,IBBB)
      EQUIVALENCE (IBB(1025),IBBP)
      COMMON /BBOARD/ IBB
cpar$ private / BBoard / ! keep FORTRAN from assigning a global section
      INTEGER ISNAP_D , ISNAP_BEFORE_1 , ISNAP_BEFORE_2 , ISNAP_AFTER_1 
     *, ISNAP_AFTER_2
      COMMON / SNAP_COMMON / ISNAP_D , ISNAP_BEFORE_1 , ISNAP_BEFORE_2 ,
     * ISNAP_AFTER_1 , ISNAP_AFTER_2
cpar$ private / snap_common / ! no FORTRAN global section
      REAL*4 REFLAT,REFLON,REFCOS,REFRNG,DLTMAX,RSQMAX,DLNMAX
      INTEGER UNT_REFERENCE
      REAL*4 SAV_REFLAT,SAV_REFLON,SAV_REFCOS,SAV_REFRNG,SAV_DLTMAX,SAV_
     *RSQMAX,SAV_DLNMAX
      INTEGER SAV_UNT_REFERENCE
      COMMON / PROXIM_COM / REFLAT,REFLON,REFCOS,RSQMAX,DLTMAX,DLNMAX,RE
     *FRNG,UNT_REFERENCE
      COMMON / SAV_PROXIM_COM / SAV_REFLAT,SAV_REFLON,SAV_REFCOS,SAV_RSQ
     *MAX,SAV_DLTMAX,SAV_DLNMAX,SAV_REFRNG,SAV_UNT_REFERENCE
CPAR$ PRIVATE / PROXIM_COM /
CPAR$ PRIVATE / SAV_PROXIM_COM /
      INTEGER INDX2
      REAL RANGE,DELLAT,FLAT,DELLON
      REAL FLON,HORIZ,RSQ,BEARING,COSLAT
      RANGE =-1.0 +(INDX2 *0)
      DELLAT =FLAT -REFLAT
      IF(.NOT.(ABS(DELLAT).LE.DLTMAX))GOTO 23039
      DELLON =FLON -REFLON
23041 IF(.NOT.(DELLON.GT.3.141592654))GOTO 23042
      DELLON =DELLON -6.283185307
      GOTO 23041
23042 CONTINUE
23043 IF(.NOT.(DELLON.LE.-3.141592654))GOTO 23044
      DELLON =DELLON +6.283185307
      GOTO 23043
23044 CONTINUE
      IF(.NOT.(ABS(DELLON).LE.DLNMAX))GOTO 23045
      HORIZ =.5*(REFCOS+COSLAT)*DELLON
      RSQ =DELLAT*DELLAT +HORIZ*HORIZ
      IF(.NOT.(RSQ.LE.RSQMAX))GOTO 23047
      IF(.NOT.(DELLAT.EQ.0.0.AND.HORIZ.EQ.0.0))GOTO 23049
      RANGE =0.0
      BEARING =0.0
      GOTO 23050
23049 CONTINUE
      RANGE =SQRT(RSQ)*(180.*60./3.141592654)
      BEARING =ATAN2(HORIZ,DELLAT)
      IF(.NOT.(BEARING.LT.0.0))GOTO 23051
      BEARING =BEARING +6.283185307
23051 CONTINUE
23050 CONTINUE
23047 CONTINUE
23045 CONTINUE
23039 CONTINUE
      RETURN
      END
      SUBROUTINE GETRB_M (KPOINT_UNT,KPOINT_UNT2,RANGE,BEARING)
      IMPLICIT NONE
      INTEGER*4 IBB(10240000)
      INTEGER*2 IBBW(2,10240000)
      BYTE IBBB(4,10240000)
      REAL*8 CBB(5120000)
      REAL FBB(10240000)
      INTEGER IBBP(6,170)
      EQUIVALENCE (IBB,FBB,CBB,IBBW,IBBB)
      EQUIVALENCE (IBB(1025),IBBP)
      COMMON /BBOARD/ IBB
cpar$ private / BBoard / ! keep FORTRAN from assigning a global section
      INTEGER ISNAP_D , ISNAP_BEFORE_1 , ISNAP_BEFORE_2 , ISNAP_AFTER_1 
     *, ISNAP_AFTER_2
      COMMON / SNAP_COMMON / ISNAP_D , ISNAP_BEFORE_1 , ISNAP_BEFORE_2 ,
     * ISNAP_AFTER_1 , ISNAP_AFTER_2
cpar$ private / snap_common / ! no FORTRAN global section
      REAL Y,DELLON,X,BEARING,RANGE
      INTEGER*4  KPOINT_UNT2
      INTEGER*4  KPOINT_UNT
C  Compute Range & Bearing
      Y =FBB(KPOINT_UNT2+19) -FBB(KPOINT_UNT+19)
      DELLON =FBB(KPOINT_UNT2+20) -FBB(KPOINT_UNT+20)
23053 IF(.NOT.(DELLON.GT.3.141592654))GOTO 23054
      DELLON =DELLON -6.283185307
      GOTO 23053
23054 CONTINUE
23055 IF(.NOT.(DELLON.LE.-3.141592654))GOTO 23056
      DELLON =DELLON +6.283185307
      GOTO 23055
23056 CONTINUE
      X =DELLON *.5 *(FBB(KPOINT_UNT+50) +FBB(KPOINT_UNT2+50))
      IF(.NOT.(X.EQ.0.0.AND.Y.EQ.0.0))GOTO 23057
      BEARING =0.0
      RANGE =0.0
      GOTO 23058
23057 CONTINUE
      RANGE =SQRT(X*X +Y*Y) *(180.*60./3.141592654)
      BEARING =ATAN2(X,Y)
      IF(.NOT.(BEARING.LT.0.0))GOTO 23059
      BEARING =BEARING +6.283185307
23059 CONTINUE
23058 CONTINUE
      RETURN
      END
