      SUBROUTINE RGSMAP (WNAME,KPAGES)
      IMPLICIT NONE
      INTEGER IRG(1025)
      REAL*8 CRG(512)
      REAL FRG(1025)
      INTEGER IRGP(6,16)
      EQUIVALENCE (IRG,FRG,CRG)
      EQUIVALENCE (IRG(513),IRGP)
      COMMON /RG_DATABASE/ IRG
      LOGICAL*1 FNAME(100),SNAME(100),SECTION_NAME(60)
      CHARACTER *(*) WNAME
      INTEGER KPAGES,NPAGES
      INTEGER ILEN,I,LENF,LENGTH,SEG$JFN,IERR
      NPAGES =KPAGES
      ILEN =0
      CALL SMOVVN (WNAME,FNAME,ILEN)
      CALL SMOV (0,FNAME,ILEN)
      CALL DEFDIR (SNAME,99)
      ILEN =0
      I=1
23000 IF(.NOT.(SNAME(I).NE.0))GOTO 23002
      IF(.NOT.(SNAME(I).EQ.91.OR.SNAME(I).EQ.93))GOTO 23003
      GOTO 23001
23003 CONTINUE
      IF(.NOT.(SNAME(I).EQ.46))GOTO 23005
      ILEN =0
      GOTO 23001
23005 CONTINUE
      CALL SMOV (SNAME(I),SECTION_NAME,ILEN)
23001 I=I+1
      GOTO 23000
23002 CONTINUE
      IF(.NOT.(ILEN.NE.0))GOTO 23007
      CALL SMOVV ('$',SECTION_NAME,ILEN)
23007 CONTINUE
      LENF =LENGTH(FNAME)
23009 IF(.NOT.(ILEN.GT.0.AND.(ILEN+LENF).GT.15))GOTO 23010
      ILEN =ILEN -1
      GOTO 23009
23010 CONTINUE
      CALL SMOVHN (FNAME,30,SECTION_NAME,ILEN)
      CALL SMOV (0,SECTION_NAME,ILEN)
      IF(.NOT.(LENGTH(SECTION_NAME).GT.15))GOTO 23011
      CALL ECHOR
      CALL ECHOV (                                                      
     *'RAINFORM Delay Data Base Logical Name is too long...')
      CALL ECHOR
      CALL ECHOV ('...Must not exceed 15 characters')
      CALL ECHOR
      CALL ECHOR
      CALL ECHOV ('Name entered is: ')
      CALL ECHOH (SECTION_NAME,90)
      CALL ECHOR
      CALL ECHOR
      STOP
23011 CONTINUE
      IF(.NOT.(NPAGES.LE.0))GOTO 23013
      RETURN
23013 CONTINUE
      NPAGES =512
      CALL FOPENM (SEG$JFN,FNAME,NPAGES,IERR)
      IF(.NOT.(IERR.NE.0))GOTO 23015
      CALL ECHOR
      CALL ECHOV ('Error on opening RAINFORM Delay data base file...')
      CALL ECHOR
      CALL TYPERR (IERR)
      CALL ECHOR
      CALL ECHOR
      STOP
23015 CONTINUE
      CALL FPMAP (SEG$JFN,SECTION_NAME,NPAGES,IRG,0,IERR)
      IF(.NOT.(IERR.EQ.0))GOTO 23017
      CALL ECHOR
      CALL ECHOV ('Error on Mapping RAINFORM Delay data base: ')
      CALL ECHOR
      CALL TYPERR (IERR)
      CALL ECHOR
      CALL ECHOR
      STOP
23017 CONTINUE
      RETURN
      END
      SUBROUTINE RGALOC (KTBLN,JNAME,NSEG,ISLOTS,IENTRY)
      IMPLICIT NONE
      INTEGER IRG(1025)
      REAL*8 CRG(512)
      REAL FRG(1025)
      INTEGER IRGP(6,16)
      EQUIVALENCE (IRG,FRG,CRG)
      EQUIVALENCE (IRG(513),IRGP)
      COMMON /RG_DATABASE/ IRG
      INTEGER LSTTBL,NSEG,ISLOTS,IENTRY,INAME
      CHARACTER *3 JNAME
      INTEGER K,KTBLN
      K=0 *NSEG
      INAME ='20202020'X
      CALL SMOVVN (JNAME,INAME,K)
      IF(.NOT.(IRG(122).LT.1025))GOTO 23019
      IRG(122)=1025
23019 CONTINUE
      IF(.NOT.(KTBLN.LT.1))GOTO 23021
      RETURN
23021 CONTINUE
      IRGP(5,KTBLN)=IENTRY
      IRGP(2,KTBLN)=ISLOTS *IABS(IENTRY)
      IRGP(4,KTBLN)=INAME
      IRGP(3,KTBLN)=0
      IRGP(1,KTBLN)=IRG(122)
      IRG(122)=IRG(122)+IRGP(2,KTBLN)
      LSTTBL =KTBLN
      RETURN
      END
      SUBROUTINE RGZAPT (KTBLN)
      IMPLICIT NONE
      INTEGER IRG(1025)
      REAL*8 CRG(512)
      REAL FRG(1025)
      INTEGER IRGP(6,16)
      EQUIVALENCE (IRG,FRG,CRG)
      EQUIVALENCE (IRG(513),IRGP)
      COMMON /RG_DATABASE/ IRG
      INTEGER KTBLN,IPNT
      IF(.NOT.(IRGP(1,KTBLN).GT.IRG(122).OR.IRGP(4,KTBLN).EQ.0))GOTO 230
     *23
      CALL ECHOR
      CALL ECHOV ('Error on Zapping table #')
      CALL ECHOI (KTBLN)
      CALL ECHOV (' (')
      CALL ECHOHN(IRGP(4,KTBLN),5)
      CALL ECHOV (').  ')
      IF(.NOT.(IRGP(4,KTBLN).EQ.0))GOTO 23025
      CALL ECHOV ('Not Defined.  ')
23025 CONTINUE
      IF(.NOT.(IRGP(1,KTBLN).GT.IRG(122)))GOTO 23027
      CALL ECHOV ('Not Mapped.')
23027 CONTINUE
      STOP
23023 CONTINUE
      IPNT =0
23029 IF(.NOT.(IPNT.LT.IRGP(2,KTBLN)))GOTO 23031
      IRG(IRGP(1,KTBLN)+IPNT) =0
23030 IPNT=IPNT+1
      GOTO 23029
23031 CONTINUE
      RETURN
      END
