      SUBROUTINE STR_TRIM (DESTINATION,SOURCE,DEST_LEN)
      IMPLICIT NONE
      CHARACTER *(*) SOURCE,DESTINATION
      INTEGER*4 DEST_LEN
      CHARACTER *1 A_CHAR
      INTEGER*4 S,D,S_LEN,D_LEN
      INTEGER LENGTH_TRIMMED
      D_LEN =LEN(DESTINATION)
      S_LEN =LENGTH_TRIMMED(SOURCE)
      D =MIN(D_LEN,S_LEN)
      DESTINATION =SOURCE(1:D)
      DEST_LEN =D
      END
      SUBROUTINE TRIM_COMPRESS (SOURCE,DESTINATION,DEST_LEN)
      IMPLICIT NONE
      CHARACTER *(*) SOURCE,DESTINATION
      INTEGER*4 DEST_LEN
      CHARACTER *1 A_CHAR
      INTEGER*4 S,D,S_LEN,D_LEN
      D =0
      DESTINATION =''
      D_LEN =LEN(DESTINATION)
      S_LEN =LEN(SOURCE)
      S =1
23000 IF(.NOT.(S.LE.S_LEN))GOTO 23002
      A_CHAR =SOURCE(S:S)
      IF(.NOT.(A_CHAR.EQ.CHAR(9)))GOTO 23003
      A_CHAR =''
23003 CONTINUE
      IF(.NOT.(A_CHAR.EQ.CHAR(10)))GOTO 23005
      A_CHAR =''
23005 CONTINUE
      IF(.NOT.(A_CHAR.EQ.''))GOTO 23007
      IF(.NOT.(D.EQ.0))GOTO 23009
      GOTO 23001
23009 CONTINUE
      IF(.NOT.(DESTINATION(D:D).EQ.''))GOTO 23011
      GOTO 23001
23011 CONTINUE
23010 CONTINUE
23007 CONTINUE
      D =D +1
      DESTINATION(D:D) =A_CHAR
      IF(.NOT.(D.GE.D_LEN))GOTO 23013
      GOTO 23002
23013 CONTINUE
23001 S=S+1
      GOTO 23000
23002 CONTINUE
      IF(.NOT.(D.GT.0))GOTO 23015
      IF(.NOT.(DESTINATION(D:D).EQ.''))GOTO 23017
      D =D -1
23017 CONTINUE
23015 CONTINUE
      DEST_LEN =D
      END
      SUBROUTINE STR_UPCASE (DESTINATION,SOURCE)
      IMPLICIT NONE
      CHARACTER *(*) SOURCE,DESTINATION
      CHARACTER *1 A_CHAR
      INTEGER*4 S,D,S_LEN,D_LEN
      D =0
      DESTINATION =''
      D_LEN =LEN(DESTINATION)
      S_LEN =LEN(SOURCE)
      S =1
23019 IF(.NOT.(S.LE.S_LEN))GOTO 23021
      A_CHAR =SOURCE(S:S)
      IF(.NOT.(A_CHAR.GE.'a'.AND.A_CHAR.LE.'z'))GOTO 23022
      A_CHAR =CHAR(ICHAR('A') +ICHAR(A_CHAR) -ICHAR('a'))
23022 CONTINUE
      D =D +1
      DESTINATION(D:D) =A_CHAR
      IF(.NOT.(D.GE.D_LEN))GOTO 23024
      GOTO 23021
23024 CONTINUE
23020 S=S+1
      GOTO 23019
23021 CONTINUE
      RETURN
      END
      INTEGER FUNCTION LENGTH_TRIMMED (TEXT )
      IMPLICIT NONE
      CHARACTER *(*) TEXT
      INTEGER IPOS,KK,A_CHAR,ICHAR
      KK =0
      IPOS =1
23026 IF(.NOT.(IPOS.LE.LEN(TEXT)))GOTO 23028
      A_CHAR =ICHAR(TEXT(IPOS:IPOS))
      IF(.NOT.(A_CHAR.EQ.0))GOTO 23029
      GOTO 23028
23029 CONTINUE
      IF(.NOT.(A_CHAR.EQ.9.OR.A_CHAR.EQ.32))GOTO 23031
      GOTO 23027
23031 CONTINUE
      KK =IPOS
23027 IPOS=IPOS+1
      GOTO 23026
23028 CONTINUE
      LENGTH_TRIMMED=(KK)
      RETURN
      END
      SUBROUTINE REMOVE_ALL_SPACES(TEXT,TEXT_LEN)
      IMPLICIT NONE
      CHARACTER *(*) TEXT
      INTEGER*4 TEXT_LEN
      INTEGER*4 I
      TEXT_LEN =0
      I =1
23033 IF(.NOT.(I.LE.LEN(TEXT)))GOTO 23035
      IF(.NOT.(TEXT(I:I).NE.' '))GOTO 23036
      TEXT_LEN =TEXT_LEN +1
      TEXT(TEXT_LEN:TEXT_LEN) =TEXT(I:I)
23036 CONTINUE
23034 I=I+1
      GOTO 23033
23035 CONTINUE
      RETURN
      END
      SUBROUTINE STR_ELEMENT (OUT_ELEMENT,ELEMENT_NUM,DELIMITER,IN_STRIN
     *G)
      IMPLICIT NONE
      CHARACTER *(*) OUT_ELEMENT
      INTEGER*4 ELEMENT_NUM
      CHARACTER *(1) DELIMITER
      CHARACTER *(*) IN_STRING
      INTEGER*2 BEGIN_ELEMENT
      INTEGER*2 END_ELEMENT
      INTEGER*2 END_IN_STRING
      INTEGER*2 ELEMENT_COUNT
      INTEGER*2 INDX
      END_IN_STRING =LEN(IN_STRING)
      IF(.NOT.(IN_STRING(END_IN_STRING:END_IN_STRING).EQ.CHAR(0)))GOTO 2
     *3038
      END_IN_STRING =END_IN_STRING -1
23038 CONTINUE
      ELEMENT_COUNT =0
      BEGIN_ELEMENT =1
      END_ELEMENT =1
      INDX =1
23040 IF(.NOT.(INDX.LE.END_IN_STRING))GOTO 23042
      IF(.NOT.(IN_STRING(INDX:INDX).EQ.DELIMITER))GOTO 23043
      ELEMENT_COUNT =ELEMENT_COUNT +1
      IF(.NOT.(ELEMENT_COUNT.EQ.1))GOTO 23045
      BEGIN_ELEMENT =1
      GOTO 23046
23045 CONTINUE
      BEGIN_ELEMENT =END_ELEMENT +2
23046 CONTINUE
      END_ELEMENT =INDX -1
23043 CONTINUE
      IF(.NOT.(ELEMENT_COUNT.EQ.ELEMENT_NUM+1))GOTO 23047
      IF(.NOT.(IN_STRING(INDX:INDX).NE.DELIMITER.OR.IN_STRING(INDX-1:IND
     *X-1).NE.DELIMITER))GOTO 23049
      OUT_ELEMENT =IN_STRING(BEGIN_ELEMENT:END_ELEMENT)
23049 CONTINUE
      GOTO 23042
23047 CONTINUE
23041 INDX=INDX+1
      GOTO 23040
23042 CONTINUE
      IF(.NOT.(ELEMENT_COUNT.NE.0))GOTO 23051
      IF(.NOT.(ELEMENT_COUNT.EQ.ELEMENT_NUM))GOTO 23053
      BEGIN_ELEMENT =END_ELEMENT +2
      OUT_ELEMENT =IN_STRING(BEGIN_ELEMENT:END_IN_STRING)
23053 CONTINUE
23051 CONTINUE
      IF(.NOT.(ELEMENT_NUM.EQ.0.AND.ELEMENT_COUNT.EQ.0))GOTO 23055
      OUT_ELEMENT =IN_STRING(BEGIN_ELEMENT:END_IN_STRING)
23055 CONTINUE
      END
