      SUBROUTINE HLTSLF
      IMPLICIT NONE
      STOP
      RETURN
      END
      INTEGER FUNCTION FIND_FILE(FNAME)
      USE IFPORT
      CHARACTER *(*) FNAME
      INTEGER ISTAT
      INTEGER FILE_STATS(13)
      ISTAT =STAT(FNAME,FILE_STATS)
      FIND_FILE =ISTAT
      RETURN
      END
      SUBROUTINE TYPERR (IERR)
      USE IFCORE
      IMPLICIT NONE
      INTEGER IERR
      CHARACTER *400MSG
      CALL GERROR(MSG)
      CALL ECHOVT(MSG)
      CALL ECHOR
      RETURN
      END
      SUBROUTINE GETERR (IERR,MSG)
      USE IFCORE
      IMPLICIT NONE
      INTEGER IERR
      LOGICAL*1 MSG(400)
      CHARACTER *400VMSG
      CALL GERROR(VMSG)
      CALL FS2RS(VMSG,MSG)
      RETURN
      END
      SUBROUTINE QUERY_DISK_INFO (DEVICE_NAME,MAX_BLOCKS,FREE_BLOCKS)
      IMPLICIT NONE
      CHARACTER *(*) DEVICE_NAME
      INTEGER*4 MAX_BLOCKS
      INTEGER*4 FREE_BLOCKS
      MAX_BLOCKS =99999999
      FREE_BLOCKS =9999999
      RETURN
      END
      INTEGER FUNCTION NOW(R)
      USE IFPORT
      IMPLICIT NONE
      REAL R
      CHARACTER *23 DATE_TIME_V
      CHARACTER *8 DATE_V
      CHARACTER *10 TIME_V
      CHARACTER *5 ZONE_V
      INTEGER SYSTIME(8)
      CALL DATE_AND_TIME (DATE_V,TIME_V,ZONE_V,SYSTIME)
      NOW =SYSTIME(5)*3600000 +SYSTIME(6)*60000 +SYSTIME(7)*1000 +SYSTIM
     *E(8) -INT(R)
      RETURN
      END
      SUBROUTINE INIT_ERRSET
      IMPLICIT NONE
      RETURN
      END
      INTEGER FUNCTION RUNTIM (DUMMY)
      USE IFPORT
      IMPLICIT NONE
      INTEGER DUMMY
      REAL CPUTIM(2),CPUTOT
      DATA CPUTOT/0.0/
      CPUTIM(1) =0.0
      CPUTIM(2) =0.0
      CPUTOT =CPUTOT +DTIME(CPUTIM)
      RUNTIM =CPUTOT *1000. +.5
      RETURN
      END
      SUBROUTINE LOGOUT
      USE IFPORT
      IMPLICIT NONE
      EXTERNAL KILL_PARENT
      INTEGER RC
      INTEGER KILL_PARENT
      RC =KILL_PARENT()
      RC =SYSTEM('exit')
      CALL HLTSLF
      RETURN
      END
      SUBROUTINE TRACE
      IMPLICIT NONE
      RETURN
      END
      SUBROUTINE SET_EXIT_HANDLER (EXIT_RTN)
      IMPLICIT NONE
      INTEGER EXIT_RTN
      CALL C_ATEXIT(EXIT_RTN)
      RETURN
      END
