      CHARACTER *(*) FUNCTION VSTRIP (CHARS,POS,NBRCHARS)
      IMPLICIT NONE
      INTEGER NBRCHARS,POS
      LOGICAL*1 CHARS(NBRCHARS)
      INTEGER I,IPOS,INTCHAR
      IPOS =POS
      I=1
23000 IF(.NOT.(I.LE.NBRCHARS))GOTO 23002
      INTCHAR =CHARS(IPOS)
      VSTRIP(I:I) =CHAR(INTCHAR)
      IPOS =IPOS +1
23001 I=I+1
      GOTO 23000
23002 CONTINUE
      RETURN
      END
      SUBROUTINE VDRESS (STRING_IN,CHARS,POS,NBRCHARS)
      IMPLICIT NONE
      INTEGER NBRCHARS,POS
      LOGICAL*1 CHARS(100)
      CHARACTER *(*) STRING_IN
      INTEGER IPOS,I,ILEN
      IPOS =POS
      ILEN =LEN(STRING_IN)
      I=1
23003 IF(.NOT.(I.LE.NBRCHARS))GOTO 23005
      IF(.NOT.(I.GT.ILEN))GOTO 23006
      CHARS(IPOS) =32
      GOTO 23007
23006 CONTINUE
      CHARS(IPOS) =ICHAR(STRING_IN(I:I))
23007 CONTINUE
      IPOS =IPOS +1
23004 I=I+1
      GOTO 23003
23005 CONTINUE
      RETURN
      END
      SUBROUTINE VMOVE (SOURCE,DEST)
      IMPLICIT NONE
      CHARACTER *(*) SOURCE,DEST
      DEST =SOURCE
      END
